import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { testMySQLConnection, createMySQLTables, createAdminUser } from '@/lib/installer-db';

const LOCK_FILE = path.join(process.cwd(), 'installed.lock');

export async function GET() {
  const isInstalled = fs.existsSync(LOCK_FILE);
  return NextResponse.json({ isInstalled });
}

export async function POST(req: NextRequest) {
  try {
    const isInstalled = fs.existsSync(LOCK_FILE);
    if (isInstalled) {
      return NextResponse.json(
        { error: 'Application is already installed. Delete installed.lock to reinstall.' },
        { status: 403 }
      );
    }

    const body = await req.json();
    const { action = 'install', dbHost = 'localhost', dbPort = 3306, dbName, dbUser, dbPass = '', adminName, adminEmail, adminPass, appUrl } = body;

    if (!dbName || !dbUser) {
      return NextResponse.json(
        { error: 'Database name and database username are required.' },
        { status: 400 }
      );
    }

    const dbConfig = {
      host: dbHost.trim(),
      port: Number(dbPort) || 3306,
      database: dbName.trim(),
      user: dbUser.trim(),
      password: dbPass,
    };

    // Action 1: Just test the connection
    if (action === 'test') {
      const testResult = await testMySQLConnection(dbConfig);
      if (!testResult.success) {
        return NextResponse.json({ error: testResult.error }, { status: 400 });
      }
      return NextResponse.json({ success: true, message: 'Database connection successful!' });
    }

    // Action 2: Run Full Installation
    if (!adminEmail || !adminPass) {
      return NextResponse.json(
        { error: 'Admin email and admin password are required.' },
        { status: 400 }
      );
    }

    // Step A: Test DB
    const testResult = await testMySQLConnection(dbConfig);
    if (!testResult.success) {
      return NextResponse.json(
        { error: `Database connection failed: ${testResult.error}` },
        { status: 400 }
      );
    }

    // Step B: Create MySQL Tables
    const tablesResult = await createMySQLTables(dbConfig);
    if (!tablesResult.success) {
      return NextResponse.json(
        { error: `Failed to create tables: ${tablesResult.error}` },
        { status: 500 }
      );
    }

    // Step C: Create Admin User
    const adminResult = await createAdminUser(dbConfig, {
      name: adminName || 'Admin',
      email: adminEmail,
      password: adminPass,
    });
    if (!adminResult.success) {
      return NextResponse.json(
        { error: `Failed to create admin: ${adminResult.error}` },
        { status: 500 }
      );
    }

    // Step D: Write .env file
    const encodedPass = encodeURIComponent(dbPass);
    const databaseUrl = `mysql://${dbConfig.user}:${encodedPass}@${dbConfig.host}:${dbConfig.port}/${dbConfig.database}`;
    const jwtSecret = crypto.randomBytes(32).toString('hex');
    const finalAppUrl = (appUrl || 'http://localhost:3000').replace(/\/$/, '');

    const envContent = `# PostCraft Configuration (Generated by Web Installer)
DATABASE_URL="${databaseUrl}"
JWT_SECRET="${jwtSecret}"
NEXT_PUBLIC_APP_URL="${finalAppUrl}"
INSTALLED="true"
`;

    fs.writeFileSync(path.join(process.cwd(), '.env'), envContent, 'utf8');

    // Update in-memory environment variables for the current running process
    process.env['DATABASE_URL'] = databaseUrl;
    process.env['JWT_SECRET'] = jwtSecret;
    const appUrlKey = 'NEXT_PUBLIC_' + 'APP_URL';
    (process.env as any)[appUrlKey] = finalAppUrl;
    process.env['INSTALLED'] = 'true';

    // Step E: Create installed.lock
    fs.writeFileSync(
      LOCK_FILE,
      JSON.stringify({ installedAt: new Date().toISOString(), db: dbConfig.database }),
      'utf8'
    );

    return NextResponse.json({
      success: true,
      message: 'PostCraft has been successfully installed and configured!',
    });
  } catch (error: any) {
    console.error('Installer API error:', error);
    return NextResponse.json(
      { error: error?.message || 'Installation encountered an unexpected error.' },
      { status: 500 }
    );
  }
}